#pragma once

#define PLUGIN_NAME "AudioAnalyzer"

#define PLUGIN_VERSION_COMPONENT_1 1
#define PLUGIN_VERSION_COMPONENT_2 2
#define PLUGIN_VERSION_COMPONENT_3 0
#define PLUGIN_VERSION_COMPONENT_4 0

#define PLUGIN_VERSION_COMPONENTS_COUNT 4

#define PLUGIN_NAME_INCLUDE_VERSIONS 0

#define COPYRIGHT_STRING "© 2021 - rxtd"
