#pragma once

#define PLUGIN_NAME "AudioAnalyzer"

#define PLUGIN_VERSION_COMPONENT_1 1
#define PLUGIN_VERSION_COMPONENT_2 1
#define PLUGIN_VERSION_COMPONENT_3 0

#define PLUGIN_VERSION_COMPONENTS_COUNT 3

#define COPYRIGHT_STRING "2019 - rxtd"
