/*
 * Copyright (C) 2019-2020 rxtd
 *
 * This Source Code Form is subject to the terms of the GNU General Public
 * License; either version 2 of the License, or (at your option) any later
 * version. If a copy of the GPL was not distributed with this file, You can
 * obtain one at <https://www.gnu.org/licenses/gpl-2.0.html>.
 */

#pragma once
#include "../SoundHandler.h"
#include "BandResampler.h"

namespace rxtd::audio_analyzer {
	class BandCascadeTransformer : public SoundHandler {
	public:
		enum class MixFunction {
			AVERAGE,
			PRODUCT,
		};

		struct Params {
		private:
			friend BandCascadeTransformer;

			istring sourceId;

			double minWeight;
			double targetWeight;
			double weightFallback;

			double zeroLevel;
			double zeroLevelHard;
			double zeroWeight;

			MixFunction mixFunction;

			// autogenerated
			friend bool operator==(const Params& lhs, const Params& rhs) {
				return lhs.sourceId == rhs.sourceId
					&& lhs.minWeight == rhs.minWeight
					&& lhs.targetWeight == rhs.targetWeight
					&& lhs.weightFallback == rhs.weightFallback
					&& lhs.zeroLevel == rhs.zeroLevel
					&& lhs.zeroLevelHard == rhs.zeroLevelHard
					&& lhs.zeroWeight == rhs.zeroWeight
					&& lhs.mixFunction == rhs.mixFunction;
			}

			friend bool operator!=(const Params& lhs, const Params& rhs) {
				return !(lhs == rhs);
			}
		};

	private:
		Params params{ };

		index samplesPerSec{ };

		SoundHandler* source = nullptr;
		BandResampler* resampler = nullptr;

		std::vector<float> resultValues{ };

		bool changed = true;
		bool analysisComputed = false;

		struct {
			string analysisString{ };
			index minCascadeUsed = -1;
			index maxCascadeUsed = -1;
			std::vector<index> bandEndCascades{ };
			bool weightError = false;
		} analysis;

		LayerData layerData;

	public:
		static std::optional<Params> parseParams(const OptionMap& optionMap, Logger& cl);

		void setParams(const Params& params, Channel channel);

		void setSamplesPerSec(index samplesPerSec) override;
		void reset() override;

		void _process(const DataSupplier& dataSupplier) override;
		void _finish() override;

		LayeredData getData() const override {
			return { &layerData, 1 };
		}

		index getStartingLayer() const override {
			return analysis.minCascadeUsed;
		}

		bool getProp(const isview& prop, utils::BufferPrinter& printer) const override;

	protected:
		isview getSourceName() const override {
			return params.sourceId;
		}

		[[nodiscard]]
		bool vCheckSources(Logger& cl) override;

	private:
		void updateValues(SoundHandler& source, BandResampler& resampler);
		void computeAnalysis(BandResampler& resampler, index startCascade, index endCascade);
	};
}
