/*
 * Copyright (C) 2019-2020 rxtd
 *
 * This Source Code Form is subject to the terms of the GNU General Public
 * License; either version 2 of the License, or (at your option) any later
 * version. If a copy of the GPL was not distributed with this file, You can
 * obtain one at <https://www.gnu.org/licenses/gpl-2.0.html>.
 */

#pragma once
#include "../SoundHandler.h"
#include "BandResampler.h"
#include "ResamplerProvider.h"

namespace rxtd::audio_analyzer {
	class legacy_FiniteTimeFilter : public ResamplerProvider {
		enum class SmoothingCurve {
			FLAT,
			LINEAR,
			EXPONENTIAL,
		};

		struct Params {
			SmoothingCurve smoothingCurve{ };
			index smoothingFactor{ };
			double exponentialFactor{ };

			// autogenerated
			friend bool operator==(const Params& lhs, const Params& rhs) {
				return lhs.smoothingCurve == rhs.smoothingCurve
					&& lhs.smoothingFactor == rhs.smoothingFactor
					&& lhs.exponentialFactor == rhs.exponentialFactor;
			}

			friend bool operator!=(const Params& lhs, const Params& rhs) {
				return !(lhs == rhs);
			}
		};

		Params params{ };

		// pastValues[Layer][FilterSize][Band]
		std::vector<utils::Vector2D<float>> pastValues;
		index pastValuesIndex = 0;

		double smoothingNormConstant{ };

	public:
		[[nodiscard]]
		bool checkSameParams(const ParamsContainer& p) const override {
			return compareParamsEquals(params, p);
		}

		[[nodiscard]]
		ParseResult parseParams(
			const OptionMap& om, Logger& cl, const Rainmeter& rain,
			index legacyNumber
		) const override;

	protected:
		[[nodiscard]]
		ConfigurationResult vConfigure(const ParamsContainer& _params, Logger& cl, ExternalData& externalData) override;

	public:
		void vProcess(ProcessContext context, ExternalData& externalData) override;

	private:
		void applyToLayer(utils::array2d_view<float> layerPastValues, array_span<float> dest) const;
	};
}
