/*
 * Copyright (C) 2020 rxtd
 *
 * This Source Code Form is subject to the terms of the GNU General Public
 * License; either version 2 of the License, or (at your option) any later
 * version. If a copy of the GPL was not distributed with this file, You can
 * obtain one at <https://www.gnu.org/licenses/gpl-2.0.html>.
 */

#pragma once
#include "../SoundHandler.h"
#include "RainmeterWrappers.h"
#include "../../../audio-utils/CustomizableValueTransformer.h"
#include "Vector2D.h"
#include "ResamplerProvider.h"

namespace rxtd::audio_analyzer {
	class SingleValueTransformer : public ResamplerProvider {
	public:
		struct Params {
			istring sourceId;

			audio_utils::CustomizableValueTransformer transformer;

			// autogenerated
			friend bool operator==(const Params& lhs, const Params& rhs) {
				return lhs.sourceId == rhs.sourceId
					&& lhs.transformer == rhs.transformer;
			}

			friend bool operator!=(const Params& lhs, const Params& rhs) {
				return !(lhs == rhs);
			}
		};

	private:
		Params params{ };

		utils::Vector2D<float> values;

		std::vector<LayerData> layers;

	public:
		bool parseParams(const OptionMap& optionMap, Logger& cl, const Rainmeter& rain, void* paramsPtr) const override;

		const Params& getParams() const {
			return params;
		}

		void setParams(const Params& value);

	protected:
		[[nodiscard]]
		isview vGetSourceName() const override {
			return params.sourceId;
		}

		[[nodiscard]]
		bool vFinishLinking(Logger& cl) override;

	public:
		void vReset() override;
		void vProcess(const DataSupplier& dataSupplier) override;

		LayeredData vGetData() const override {
			return layers;
		}

		[[nodiscard]]
		DataSize getDataSize() const override {
			return { values.getBuffersCount(), values.getBufferSize() };
		}
	};
}
