#pragma once

#define PLUGIN_NAME "LocalPluginLoader"

#define PLUGIN_VERSION_COMPONENT_1 1
#define PLUGIN_VERSION_COMPONENT_2 0
#define PLUGIN_VERSION_COMPONENT_3 2

#define PLUGIN_VERSION_COMPONENTS_COUNT 3

#define COPYRIGHT_STRING "2018-2019 - rxtd"
