#pragma once

#define PLUGIN_NAME "PerfMonRxtd"

#define PLUGIN_VERSION_COMPONENT_1 1
#define PLUGIN_VERSION_COMPONENT_2 2
#define PLUGIN_VERSION_COMPONENT_3 3

#define PLUGIN_VERSION_COMPONENTS_COUNT 3

#define PLUGIN_NAME_INCLUDE_VERSIONS 2

#define COPYRIGHT_STRING "2018-2019 - rxtd, 2018 - buckb"
