// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2020 Danil Uzlov

#pragma once
#include "rxtd/audio_analyzer/audio_utils/CustomizableValueTransformer.h"
#include "rxtd/audio_analyzer/sound_processing/sound_handlers/HandlerBase.h"

namespace rxtd::audio_analyzer::handler {
	class Loudness : public HandlerBase {
		using CVT = audio_utils::CustomizableValueTransformer;

		struct Params {
			CVT transformer{};
			double gatingLimit{};
			double updatesPerSecond{};
			double timeWindowMs{};
			double gatingDb{};
			bool ignoreGatingForSilence{};

			// autogenerated
			friend bool operator==(const Params& lhs, const Params& rhs) {
				return lhs.transformer == rhs.transformer
					&& lhs.gatingLimit == rhs.gatingLimit
					&& lhs.updatesPerSecond == rhs.updatesPerSecond
					&& lhs.timeWindowMs == rhs.timeWindowMs
					&& lhs.gatingDb == rhs.gatingDb
					&& lhs.ignoreGatingForSilence == rhs.ignoreGatingForSilence;
			}

			friend bool operator!=(const Params& lhs, const Params& rhs) {
				return !(lhs == rhs);
			}
		};

		Params params{};

		index blocksCount{};
		index blockSize{};
		double blockNormalizer{};
		index blockCounter{};

		double blockIntermediate{};
		std::vector<double> blocks;
		index nextBlockIndex{};
		std::vector<double> tempBlocks;

		double prevValue{};
		double gatingValueCoefficient{};
		index minBlocksCount{};

	public:
		[[nodiscard]]
		bool vCheckSameParams(const ParamsContainer& p) const override {
			return compareParamsEquals(params, p);
		}

		[[nodiscard]]
		ParamsContainer vParseParams(ParamParseContext& context) const noexcept(false) override;

	protected:
		[[nodiscard]]
		ConfigurationResult vConfigure(const ParamsContainer& _params, Logger& cl, ExternalData& externalData) override;

		void vProcess(ProcessContext context, ExternalData& externalData) override;

		void pushMicroBlock(double value);

	private:
		void pushNextValue(double value);
	};
}
