/*
 * Copyright (C) 2019-2020 rxtd
 *
 * This Source Code Form is subject to the terms of the GNU General Public
 * License; either version 2 of the License, or (at your option) any later
 * version. If a copy of the GPL was not distributed with this file, You can
 * obtain one at <https://www.gnu.org/licenses/gpl-2.0.html>.
 */

#pragma once
#include "SoundHandler.h"
#include "RainmeterWrappers.h"

namespace rxtd::audio_analyzer {
	class BlockHandler : public SoundHandler {
	public:
		enum class TransformType {
			eFILTER,
			eDB,
			eMAP,
			eCLAMP,
		};

		struct Transformation {
			TransformType type{ };
			double args[4]{ };
			mutable void* state;

			~Transformation();

			// autogenerated
			friend bool operator==(const Transformation& lhs, const Transformation& rhs) {
				return lhs.type == rhs.type;
			}

			friend bool operator!=(const Transformation& lhs, const Transformation& rhs) {
				return !(lhs == rhs);
			}
		};

		struct Params {
		private:
			friend BlockHandler;

			double resolution{ };
			bool subtractMean{ };
			std::vector<Transformation> transformations;

			// autogenerated
			friend bool operator==(const Params& lhs, const Params& rhs) {
				return lhs.resolution == rhs.resolution
					&& lhs.subtractMean == rhs.subtractMean
					&& lhs.transformations == rhs.transformations;
			}

			friend bool operator!=(const Params& lhs, const Params& rhs) {
				return !(lhs == rhs);
			}
		};

	private:
		Params params{ };

		index samplesPerSec{ };
		index blockSize{ };

	protected:
		index counter = 0;

	private:
		float result = 0.0;

		mutable string propString{ };

	public:
		void setParams(Params params, Channel channel);

		void setSamplesPerSec(index samplesPerSec) final;
		void reset() final;

		void process(const DataSupplier& dataSupplier) final;
		void processSilence(const DataSupplier& dataSupplier) final;

		void finish(const DataSupplier& dataSupplier) final {
		}

		array_view<float> getData(layer_t layer) const final {
			return { &result, 1 };
		}

		const wchar_t* getProp(const isview& prop) const override;

		static std::optional<Params> parseParams(const utils::OptionMap& optionMap, utils::Rainmeter::Logger& cl);

	protected:
		void setNextValue(double value);

		index getBlockSize() const {
			return blockSize;
		}

	private:
		static std::optional<Transformation> parseTransformation(utils::OptionList list, utils::Rainmeter::Logger& cl);
		void recalculateConstants();
		void updateTransformations();
		void resetTransformationStates();

	protected:
		virtual void _process(array_view<float> wave, float average) = 0;
		virtual void finishBlock() = 0;
		virtual void _reset() = 0;

		virtual void _setSamplesPerSec(index samplesPerSec) {
		}

		virtual bool isAverageNeeded() const {
			return false;
		}

		virtual sview getDefaultTransform() = 0;
	};

	class BlockRms : public BlockHandler {
		double intermediateResult = 0.0;

	public:
		void _process(array_view<float> wave, float average) override;

	protected:
		bool isAverageNeeded() const override {
			return true;
		}

		void finishBlock() override;
		void _reset() override;
		sview getDefaultTransform() override;
	};

	class BlockPeak : public BlockHandler {
		double intermediateResult = 0.0;

	public:
		void _process(array_view<float> wave, float average) override;

	protected:
		void finishBlock() override;
		void _reset() override;
		sview getDefaultTransform() override;
	};
}
