/*
 * Copyright (C) 2019-2020 rxtd
 *
 * This Source Code Form is subject to the terms of the GNU General Public
 * License; either version 2 of the License, or (at your option) any later
 * version. If a copy of the GPL was not distributed with this file, You can
 * obtain one at <https://www.gnu.org/licenses/gpl-2.0.html>.
 */

#pragma once
#include "SoundHandler.h"
#include "RainmeterWrappers.h"
#include "../../audio-utils/CustomizableValueTransformer.h"

namespace rxtd::audio_analyzer {
	class BlockHandler : public SoundHandler {
		using CVT = audio_utils::CustomizableValueTransformer;

	public:
		struct Params {
			double resolution{ };
			bool subtractMean{ };
			string transform{ };

			double legacy_attackTime{};
			double legacy_decayTime{};
			audio_utils::CustomizableValueTransformer transformer{ };

			// autogenerated
			friend bool operator==(const Params& lhs, const Params& rhs) {
				return lhs.resolution == rhs.resolution
					&& lhs.subtractMean == rhs.subtractMean
					&& lhs.transform == rhs.transform;
			}

			friend bool operator!=(const Params& lhs, const Params& rhs) {
				return !(lhs == rhs);
			}
		};

	private:
		Params params{ };

		index blockSize{ };

		float result = 0.0;
		LayerData resultL;

	protected:
		index counter = 0;

	public:
		bool parseParams(const OptionMap& optionMap, Logger& cl, const Rainmeter& rain, void* paramsPtr) const override;

		const Params& getParams() const {
			return params;
		}

		void setParams(const Params& value);

	protected:
		[[nodiscard]]
		isview vGetSourceName() const override {
			return { };
		}

		[[nodiscard]]
		bool vFinishLinking(Logger& cl) override;

	public:
		void vReset() final;
		void vProcess(const DataSupplier& dataSupplier) final;

		LayeredData vGetData() const override {
			return { &resultL, 1 };
		}

		[[nodiscard]]
		DataSize getDataSize() const override {
			return { 1, 1 };
		}

		bool vGetProp(const isview& prop, utils::BufferPrinter& printer) const override;

	protected:
		void setNextValue(double value);

		index getBlockSize() const {
			return blockSize;
		}

		virtual void _process(array_view<float> wave, float average) = 0;
		virtual void finishBlock() = 0;
		virtual void _reset() = 0;

		virtual bool isAverageNeeded() const {
			return false;
		}

		virtual sview getDefaultTransform() = 0;
	};


	class BlockRms : public BlockHandler {
		double intermediateResult = 0.0;

	public:
		void _process(array_view<float> wave, float average) override;

	protected:
		bool isAverageNeeded() const override {
			return true;
		}

		void finishBlock() override;
		void _reset() override;
		sview getDefaultTransform() override;
	};

	class BlockPeak : public BlockHandler {
		double intermediateResult = 0.0;

	public:
		void _process(array_view<float> wave, float average) override;

	protected:
		void finishBlock() override;
		void _reset() override;
		sview getDefaultTransform() override;
	};
}
