/*
 * Copyright (C) 2020 rxtd
 *
 * This Source Code Form is subject to the terms of the GNU General Public
 * License; either version 2 of the License, or (at your option) any later
 * version. If a copy of the GPL was not distributed with this file, You can
 * obtain one at <https://www.gnu.org/licenses/gpl-2.0.html>.
 */

#pragma once
#include "StripedImage.h"
#include "DiscreetInterpolator.h"
#include "Color.h"

namespace rxtd::utils {
	class WaveFormDrawer {
	public:
		enum class LineDrawingPolicy {
			eNEVER,
			eBELOW_WAVE,
			eALWAYS,
		};

		enum class SmoothEdges {
			eNONE,
			eMIN_MAX,
			eHALO,
		};

		enum class FadingType {
			eNONE,
			eLINEAR,
			ePOW2,
			ePOW4,
			ePOW8,
		};

		struct Colors {
			Color background;
			Color wave;
			Color line;
			Color border;
			Color halo;

			// autogenerated
			friend bool operator==(const Colors& lhs, const Colors& rhs) {
				return lhs.background == rhs.background
					&& lhs.wave == rhs.wave
					&& lhs.line == rhs.line
					&& lhs.border == rhs.border
					&& lhs.halo == rhs.halo;
			}

			friend bool operator!=(const Colors& lhs, const Colors& rhs) {
				return !(lhs == rhs);
			}
		};

	private:
		StripedImage<float> inflatableBuffer{ };
		Vector2D<uint32_t> resultBuffer{ };
		std::vector<float> stripBuffer{ };
		DiscreetInterpolator interpolator;

		index width{ };
		index height{ };

		LineDrawingPolicy lineDrawingPolicy = LineDrawingPolicy::eNEVER;
		SmoothEdges edges = SmoothEdges::eNONE;
		bool connected = false;
		index borderSize = 0;
		FadingType fading = FadingType::eNONE;

		Colors colors;

		struct {
			double min = 0.0;
			double max = 0.0;
		} prev;

		float inflatingPrev = 0.0;

	public:
		WaveFormDrawer();

		void setEdges(SmoothEdges value) {
			edges = value;
		}

		void setConnected(bool value) {
			connected = value;
		}

		void setBorderSize(index value) {
			borderSize = value;
		}

		void setFading(FadingType value) {
			fading = value;
		}

		void setStationary(bool value) {
			inflatableBuffer.setStationary(value);
		}

		void setLineDrawingPolicy(LineDrawingPolicy value) {
			lineDrawingPolicy = value;
		}

		void setColors(Colors value) {
			colors = value;
		}

		void setDimensions(index width, index height);

		void fillSilence();

		void fillStrip(double min, double max);

		array2d_view<uint32_t> getResultBuffer() const {
			return resultBuffer;
		}

		bool isEmpty() const {
			const index lastStripIndex = inflatableBuffer.getLastStripIndex();
			const bool needMoreUpdates = (fading != FadingType::eNONE || borderSize != 0)
				&& lastStripIndex != width - 1;

			return !needMoreUpdates && inflatableBuffer.isEmpty();
		}

		void inflate();

	private:
		void inflateLine(array_view<float> source, array_span<uint32_t> dest) {
			switch (fading) {
			case FadingType::eNONE:
				inflateLine<distNone>(source, dest);
				break;
			case FadingType::eLINEAR:
				inflateLine<distLinear>(source, dest);
				break;
			case FadingType::ePOW2:
				inflateLine<distPow2>(source, dest);
				break;
			case FadingType::ePOW4:
				inflateLine<distPow4>(source, dest);
				break;
			case FadingType::ePOW8:
				inflateLine<distPow8>(source, dest);
				break;
			default: ;
			}
		}

		template<double (*distanceTransformFunc)(double)>
		void inflateLine(array_view<float> source, array_span<uint32_t> dest) {
			const index lastStripIndex = inflatableBuffer.getLastStripIndex();
			const double realWidth = width - borderSize;
			const double distanceCoef = 1.0 / realWidth;

			for (int i = 0; i < width; ++i) {
				double distance = lastStripIndex - i;
				if (distance < 0.0) {
					distance += width;
				}
				if (distance >= realWidth) {
					// this is border
					dest[i] = colors.border.toInt();
					continue;
				}

				distance *= distanceCoef;
				distance = distanceTransformFunc(distance);

				dest[i] = inflatePixel(source, distance, i);
			}
		}

		uint32_t inflatePixel(array_view<float> source, double backgroundCoef, index i);

		std::pair<double, double> correctMinMaxPixels(double minPixel, double maxPixel) const;

		void fillStripBuffer(double min, double max);

		static double distNone(double) {
			return 0.0;
		}

		static double distLinear(double value) {
			return value;
		}

		static double distPow2(double value) {
			value = value * value;
			return value;
		}

		static double distPow4(double value) {
			value = value * value;
			value = value * value;
			return value;
		}

		static double distPow8(double value) {
			value = value * value;
			value = value * value;
			value = value * value;
			return value;
		}
	};
}
