/*
 * Copyright (C) 2019-2020 rxtd
 *
 * This Source Code Form is subject to the terms of the GNU General Public
 * License; either version 2 of the License, or (at your option) any later
 * version. If a copy of the GPL was not distributed with this file, You can
 * obtain one at <https://www.gnu.org/licenses/gpl-2.0.html>.
 */

#pragma once
#include "HandlerCacheHelper.h"

namespace rxtd::audio_analyzer {
	struct HandlerPatchersInfo {
		std::vector<istring> order;
		std::map<istring, PatchInfo, std::less<>> patchers;

		// autogenerated
		friend bool operator==(const HandlerPatchersInfo& lhs, const HandlerPatchersInfo& rhs) {
			return lhs.order == rhs.order
				&& lhs.patchers == rhs.patchers;
		}

		friend bool operator!=(const HandlerPatchersInfo& lhs, const HandlerPatchersInfo& rhs) {
			return !(lhs == rhs);
		}
	};
}
