/*
 * Copyright (C) 2020-2021 rxtd
 *
 * This Source Code Form is subject to the terms of the GNU General Public
 * License; either version 2 of the License, or (at your option) any later
 * version. If a copy of the GPL was not distributed with this file, You can
 * obtain one at <https://www.gnu.org/licenses/gpl-2.0.html>.
 */

#pragma once
#include "sound-processing/sound-handlers/HandlerBase.h"

namespace rxtd::audio_analyzer {
	using handlerUptr = std::unique_ptr<handler::HandlerBase>;
	using HandlerPatchFun = handlerUptr(*)(handlerUptr old);

	struct PatchInfo {
		string rawDescription;
		string rawDescription2;
		istring type;
		handler::ParamsContainer params;
		std::vector<istring> sources;
		HandlerPatchFun fun = nullptr;
		handler::ExternalMethods externalMethods{};

		// autogenerated
		friend bool operator==(const PatchInfo& lhs, const PatchInfo& rhs) {
			return lhs.rawDescription == rhs.rawDescription
				&& lhs.rawDescription2 == rhs.rawDescription2
				&& lhs.sources == rhs.sources
				&& lhs.fun == rhs.fun
				&& lhs.externalMethods == rhs.externalMethods;
		}

		friend bool operator!=(const PatchInfo& lhs, const PatchInfo& rhs) {
			return !(lhs == rhs);
		}
	};
}
