#pragma once

#include "local-version.h"

#define _MAKE_STRING(s) #s
#define MAKE_STRING(s) _MAKE_STRING(s)

#ifdef _WIN64
#define BITNESS_STRING " (64 bit)"
#else
#define BITNESS_STRING " (32 bit)"
#endif


#define TARGET_RAINMETER_VERSION_1 4
#define TARGET_RAINMETER_VERSION_2 2
#define TARGET_RAINMETER_VERSION_3 0
#define TARGET_RAINMETER_VERSION_4 3111

#define TARGET_RAINMETER_VERSION TARGET_RAINMETER_VERSION_1,TARGET_RAINMETER_VERSION_2,TARGET_RAINMETER_VERSION_3,TARGET_RAINMETER_VERSION_4
#define TARGET_RAINMETER_VERSION_STRING \
	MAKE_STRING(TARGET_RAINMETER_VERSION_1) "." \
	MAKE_STRING(TARGET_RAINMETER_VERSION_2) "." \
	MAKE_STRING(TARGET_RAINMETER_VERSION_3) "." \
	MAKE_STRING(TARGET_RAINMETER_VERSION_4)

#if (PLUGIN_VERSION_COMPONENTS_COUNT <= 2)

#define PLUGIN_VERSION PLUGIN_VERSION_COMPONENT_1,PLUGIN_VERSION_COMPONENT_2
#define PLUGIN_VERSION_STRING \
	MAKE_STRING(PLUGIN_VERSION_COMPONENT_1) "." \
	MAKE_STRING(PLUGIN_VERSION_COMPONENT_2)

#elif (PLUGIN_VERSION_COMPONENTS_COUNT == 3)

#define PLUGIN_VERSION PLUGIN_VERSION_COMPONENT_1,PLUGIN_VERSION_COMPONENT_2,PLUGIN_VERSION_COMPONENT_3
#define PLUGIN_VERSION_STRING \
	MAKE_STRING(PLUGIN_VERSION_COMPONENT_1) "." \
	MAKE_STRING(PLUGIN_VERSION_COMPONENT_2) "." \
	MAKE_STRING(PLUGIN_VERSION_COMPONENT_3)

#else

#define PLUGIN_VERSION PLUGIN_VERSION_COMPONENT_1,PLUGIN_VERSION_COMPONENT_2,PLUGIN_VERSION_COMPONENT_3,PLUGIN_VERSION_COMPONENT_4
#define PLUGIN_VERSION_STRING \
	MAKE_STRING(PLUGIN_VERSION_COMPONENT_1) "." \
	MAKE_STRING(PLUGIN_VERSION_COMPONENT_2) "." \
	MAKE_STRING(PLUGIN_VERSION_COMPONENT_3) "." \
	MAKE_STRING(PLUGIN_VERSION_COMPONENT_4)

#endif

#if (PLUGIN_NAME_INCLUDE_VERSIONS == 0)

#define FINAL_PLUGIN_NAME PLUGIN_NAME

#elif (PLUGIN_NAME_INCLUDE_VERSIONS == 1)

#define FINAL_PLUGIN_NAME PLUGIN_NAME "-v" \
	MAKE_STRING(PLUGIN_VERSION_COMPONENT_1)

#else

#define FINAL_PLUGIN_NAME PLUGIN_NAME "-v" \
	MAKE_STRING(PLUGIN_VERSION_COMPONENT_1) "." \
	MAKE_STRING(PLUGIN_VERSION_COMPONENT_2)

#endif

